redis:
  address: ${REDIS_ADDRESS|localhost:6379}
  auth: null

server:
  address: :50051

token:
  jwtSecret: ${JWT_SECRET}
  expiration: 720h00m00s

limit:
  maxMessageInGetRequest: 50

log:
  level: ${LOG_LEVEL|trace}