name: confidential_communication
description: A sample libary to communicato securily using x3dh
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  libsignal_protocol_dart: ^0.7.1
  grpc: ^3.2.0
  libsignal_protocol_hive_store: ^0.0.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
